### ISSUE TITLE
lmtp error

### ISSUE THREAD

**Issue by ghost** [1it/docker-mail#2]
Hello,

thx for sharing your work, its my favoritepostfix(admin) implementation.

One question please:
2019-04-11T19:41:56.554496+00:00 09ad1b99d14b postfix/lmtp[238]: 87F043F2BE: to=<info@domain.de>, relay=none, delay=2370, delays=2370/0.07/0/0, dsn=4.4.1, status=deferred (connect to 172.20.0.6[172.20.0.6]:2525: Connection refused)

income mail dont work, lmtp (dovecote?) refused connection. You have a hint for this problem?
thx

**Comment by 1it** [comment]
Hi,

I think you changed the port number (for lmtp) but didn’t change the links somewhere else, or container restarted and changed address. Anyway, it’s kind of misconfiguration in your case.

**Comment by ghost** [comment]
in postfix conf you use 2525, in dovecot 24 for lmtp ... i changed postfix conf, now it runs ...

**Comment by 1it** [comment]
Oh, now I see. My fault, thank you.
